--[[
	Specific constants only used on the server
]]

local Constants = {
	["NOTIFICATION_SUCCESS_SIMPLE"] = "Successfully %s %s!",
	["NOTIFICATION_ERROR"] = "An error occurred%s, please try again",
	["CASH_ADDED_STRING_FORMAT"] = "%s has been added to your cash balance!",
	["DISCOVERY_MESSAGE_STRING_FORMAT"] = `<stroke color="#000000" thickness="1">%s discovered a <font color="%s">%s %s!</font></stroke>`,
	["DISCOVERY_MESSAGE_RELIC_STRING_FORMAT"] = `<stroke color="#000000" thickness="1">%s discovered a <font color="%s">Special %s!</font></stroke>`
}

return Constants